config/routes.rb
Rails.application.routes.draw do
  root                'pages#home'
  get    'about'   => 'pages#about'
  get    'help'    => 'pages#help'
  get    'contact' => 'pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers #, :posts, :contests
    end
  end
  resources :account_activations, only: :edit
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts
  resources :contests
  resources :relationships,       only: [:create, :destroy]
end

app/models/contest.rb
class Contest < ActiveRecord::Base
  belongs_to :user
  has_many   :challenges
  has_many   :posts, through: :challenges
  default_scope -> { order(created_at: :desc) }
  validates  :user_id, presence: true
  validates  :title,  presence: true, length: { minimum: 3, maximum: 30 }
  validates  :poster, presence: true
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user,   only:                [:edit, :update, :destroy]

  def index
    @contests = Contest.all
  end

  def show
    @contest = Contest.find(params[:id])
  end

  def new
    @contest = Contest.new
  end

  def edit
  end

  def create
    @contest = current_user.contests.build(contest_params)
    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'your contest was successfully created' }
        format.json { render :show, status: :created, location: @contest }
      else
        format.html { render :new }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'your contest was successfully updated' }
        format.json { render :show, status: :ok, location: @contest }
      else
        format.html { render :edit }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url, notice: 'your contest was successfully destroyed' }
      format.json { head :no_content }
    end
  end

  private

    def correct_user
      @contest = current_user.contests.find_by(id: params[:id])
      if @contest.nil?
        redirect_to(root_url)
        flash[:warning] = "you can't update or delete somebody else's contests"
      end
    end

    def contest_params
      params.require(:contest).permit(:title, :poster, :description, :poll)
    end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_form.html.erb
<%= form_for(@contest) do |f| %>
  <% if @contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% @contest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :poster %><br>
    <%= f.text_field :poster %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :poll %><br>
    <%= f.check_box :poll %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contests/edit.html.erb
<h1>Editing Contest</h1>

<%= render 'form' %>

<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>

app/views/contests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contests</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Poster</th>
      <th>Description</th>
      <th>User</th>
      <th>Poll</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contests.each do |contest| %>
      <tr>
        <td><%= contest.title %></td>
        <td><%= contest.poster %></td>
        <td><%= contest.description %></td>
        <td><%= contest.user %></td>
        <td><%= contest.poll %></td>
        <td><%= link_to 'Show', contest %></td>
        <td><%= link_to 'Edit', edit_contest_path(contest) %></td>
        <td><%= link_to 'Destroy', contest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contest', new_contest_path %>

app/views/contests/new.html.erb
<h1>New Contest</h1>

<%= render 'form' %>

<%= link_to 'Back', contests_path %>

app/views/contests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @contest.title %>
</p>

<p>
  <strong>Poster:</strong>
  <%= @contest.poster %>
</p>

<p>
  <strong>Description:</strong>
  <%= @contest.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @contest.user %>
</p>

<p>
  <strong>Poll:</strong>
  <%= @contest.poll %>
</p>

<%= link_to 'Edit', edit_contest_path(@contest) %> |
<%= link_to 'Back', contests_path %>