config/routes.rb
Rails.application.routes.draw do
  root                'pages#home'
  get    'about'   => 'pages#about'
  get    'help'    => 'pages#help'
  get    'contact' => 'pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers #, :posts, :contests
    end
  end
  resources :account_activations, only: :edit
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts
  resources :contests
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr/>
      <div class="large-6 columns">
        <p>Tookiti © <%= Time.now.year %></p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><%= link_to "Home",    contact_path %></li>
          <li><%= link_to "About",   about_path   %></li>
          <li><%= link_to "Help",    help_path    %></li>
          <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </div>
  </div>
</footer>

app/views/layouts/_footer.html.haml
%footer
  .large-12.columns
    .large-6.columns
      %p 
        Tookiti © #{Time.now.year}
    .large-6.columns 
      %ul.inline-list.right
        %li= link_to "home",    contact_path
        %li= link_to "about",   about_path
        %li= link_to "help",    help_path
        %li= link_to "contact", contact_path

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "TookiTi!", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "home", root_path %></li>
      <% if logged_in? %>
        <li class="divider"></li>
        <li><%= link_to 'users', 'users_path' %></li>
        <li class="divider"></li>
        <li class="has-dropdown">
          <%= link_to 'profile', current_user %>
          <ul class="dropdown">
            <li><%= link_to 'settings', '#' %></li>
            <li class="divider"></li>
            <li><%= link_to 'log out', logout_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li class="divider"></li>
        <li class="has-form">
          <%= link_to 'sign up', signup_path, class: 'button alert radius' %>
        </li>
        <li class="divider"></li>
        <li class="has-form">
          <%= link_to 'log in', login_path, class: 'button success radius' %>
        </li>
        <li class="divider"></li>
        <li class="has-dropdown">
          <a href="#">more</a>
          <ul class="dropdown">
            <li><%= link_to "about", about_path %></li>
            <li><%= link_to "help", help_path %></li>
            <li><%= link_to "contact", contact_path %></li>
          </ul>
      </li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/_header.html.haml
%nav.top-bar{"data-topbar" => ""}
  %ul.title-area
    %li.name
      %h1= link_to("TookiTi!", root_path)
    %li.toggle-topbar.menu-icon
      %a{href: '#'}
        %span menu
  %section.top-bar-section
    %ul.right
      - if logged_in?
        %li.divider
        %li.has-dropdown
          = link_to('posts', '#')
          %ul.dropdown
            %li= link_to('all posts', posts_path)
            %li.divider
            %li= link_to('new post',  new_post_path)
        %li.divider
        %li= link_to('users',  users_path)
        %li.divider
        %li.has-dropdown
          = link_to('profile', current_user)
          %ul.dropdown
            %li= link_to('settings', edit_user_path(current_user))
            %li.divider
            %li= link_to('logout',   logout_path, method: :delete)
      - else
        %li.divider
        %li= link_to('home',     root_path)
        %li.divider
        %li= link_to('posts',    posts_path)
        %li.divider
        %li.has-form
          = link_to('sign up', signup_path,  class: 'button alert radius')
        %li.divider
        %li.has-form 
          = link_to('log in',  login_path,   class: 'button success radius')
        %li.divider
        %li.has-dropdown
          = link_to('more', '#') 
          %ul.dropdown
            %li= link_to('about',   about_path)
            %li= link_to('help',    help_path)
            %li= link_to('contact', contact_path)

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? full_title(yield(:title)) : "Tookiti" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>

  	<%= render 'layouts/header' %>

    <div class="row full_width">
      <% flash.each do |msg_type, msg| %>
        <div data-alert class="alert-box <%= msg_type %>"><%= msg %></div>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>

     
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html{:lang => 'en'}
  %head
    %meta{charset: 'utf-8'}/
    %meta{content: 'width=device-width, initial-scale=1.0',  name: 'viewport'}/
    %title= content_for(:title) ? full_title(yield(:title)) : 'TookiTi!'
    = stylesheet_link_tag('application')
    = javascript_include_tag('vendor/modernizr')
    = csrf_meta_tags
    = render('layouts/shim')
  %body
    = render('layouts/header')
    .row.full_width
      - flash.each do |msg_type, msg|
        %div{class: "alert-box #{msg_type}", 'data-alert' => ''}= msg
      = yield
    .row.footer
      = render('layouts/footer')
      = javascript_include_tag('application')